package web

// generated by internal/dog.go
func A(c ...interface{}) *Element {
	return NewElement("a", c...)
}
func Abbr(c ...interface{}) *Element {
	return NewElement("abbr", c...)
}
func Acronym(c ...interface{}) *Element {
	return NewElement("acronym", c...)
}
func Address(c ...interface{}) *Element {
	return NewElement("address", c...)
}
func Article(c ...interface{}) *Element {
	return NewElement("article", c...)
}
func Aside(c ...interface{}) *Element {
	return NewElement("aside", c...)
}
func B(c ...interface{}) *Element {
	return NewElement("b", c...)
}
func Big(c ...interface{}) *Element {
	return NewElement("big", c...)
}
func Blockquote(c ...interface{}) *Element {
	return NewElement("blockquote", c...)
}
func Body(c ...interface{}) *Element {
	return NewElement("body", c...)
}
func Button(c ...interface{}) *Element {
	return NewElement("button", c...)
}
func Cite(c ...interface{}) *Element {
	return NewElement("cite", c...)
}
func Code(c ...interface{}) *Element {
	return NewElement("code", c...)
}
func Dd(c ...interface{}) *Element {
	return NewElement("dd", c...)
}
func Del(c ...interface{}) *Element {
	return NewElement("del", c...)
}
func Details(c ...interface{}) *Element {
	return NewElement("details", c...)
}
func Dfn(c ...interface{}) *Element {
	return NewElement("dfn", c...)
}
func Div(c ...interface{}) *Element {
	return NewElement("div", c...)
}
func Dl(c ...interface{}) *Element {
	return NewElement("dl", c...)
}
func Dt(c ...interface{}) *Element {
	return NewElement("dt", c...)
}
func Footer(c ...interface{}) *Element {
	return NewElement("footer", c...)
}
func Form(c ...interface{}) *Element {
	return NewElement("form", c...)
}
func H1(c ...interface{}) *Element {
	return NewElement("h1", c...)
}
func H2(c ...interface{}) *Element {
	return NewElement("h2", c...)
}
func H3(c ...interface{}) *Element {
	return NewElement("h3", c...)
}
func H4(c ...interface{}) *Element {
	return NewElement("h4", c...)
}
func H5(c ...interface{}) *Element {
	return NewElement("h5", c...)
}
func H6(c ...interface{}) *Element {
	return NewElement("h6", c...)
}
func Head(c ...interface{}) *Element {
	return NewElement("head", c...)
}
func Header(c ...interface{}) *Element {
	return NewElement("header", c...)
}
func Hgroup(c ...interface{}) *Element {
	return NewElement("hgroup", c...)
}
func I(c ...interface{}) *Element {
	return NewElement("i", c...)
}
func Ins(c ...interface{}) *Element {
	return NewElement("ins", c...)
}
func Kbd(c ...interface{}) *Element {
	return NewElement("kbd", c...)
}
func Label(c ...interface{}) *Element {
	return NewElement("label", c...)
}
func Legend(c ...interface{}) *Element {
	return NewElement("legend", c...)
}
func Li(c ...interface{}) *Element {
	return NewElement("li", c...)
}
func Mark(c ...interface{}) *Element {
	return NewElement("mark", c...)
}
func Menu(c ...interface{}) *Element {
	return NewElement("menu", c...)
}
func Meter(c ...interface{}) *Element {
	return NewElement("meter", c...)
}
func Nav(c ...interface{}) *Element {
	return NewElement("nav", c...)
}
func Noscript(c ...interface{}) *Element {
	return NewElement("noscript", c...)
}
func Ol(c ...interface{}) *Element {
	return NewElement("ol", c...)
}
func Optgroup(c ...interface{}) *Element {
	return NewElement("optgroup", c...)
}
func Option(c ...interface{}) *Element {
	return NewElement("option", c...)
}
func Output(c ...interface{}) *Element {
	return NewElement("output", c...)
}
func P(c ...interface{}) *Element {
	return NewElement("p", c...)
}
func Pre(c ...interface{}) *Element {
	return NewElement("pre", c...)
}
func Quote(c ...interface{}) *Element {
	return NewElement("quote", c...)
}
func Script(c ...interface{}) *Element {
	return NewElement("script", c...)
}
func Section(c ...interface{}) *Element {
	return NewElement("section", c...)
}
func Select(c ...interface{}) *Element {
	return NewElement("select", c...)
}
func Span(c ...interface{}) *Element {
	return NewElement("span", c...)
}
func Style(c ...interface{}) *Element {
	return NewElement("style", c...)
}
func Sub(c ...interface{}) *Element {
	return NewElement("sub", c...)
}
func Summary(c ...interface{}) *Element {
	return NewElement("summary", c...)
}
func Sup(c ...interface{}) *Element {
	return NewElement("sup", c...)
}
func Table(c ...interface{}) *Element {
	return NewElement("table", c...)
}
func Tbody(c ...interface{}) *Element {
	return NewElement("tbody", c...)
}
func Td(c ...interface{}) *Element {
	return NewElement("td", c...)
}
func Textarea(c ...interface{}) *Element {
	return NewElement("textarea", c...)
}
func Th(c ...interface{}) *Element {
	return NewElement("th", c...)
}
func Thead(c ...interface{}) *Element {
	return NewElement("thead", c...)
}
func Title(c ...interface{}) *Element {
	return NewElement("title", c...)
}
func Tr(c ...interface{}) *Element {
	return NewElement("tr", c...)
}
func U(c ...interface{}) *Element {
	return NewElement("u", c...)
}
func Ul(c ...interface{}) *Element {
	return NewElement("ul", c...)
}
func Var(c ...interface{}) *Element {
	return NewElement("var", c...)
}

func Base(c ...interface{}) *Element {
	return NewSimpleElement("base", c...)
}
func Br(c ...interface{}) *Element {
	return NewSimpleElement("br", c...)
}
func Hr(c ...interface{}) *Element {
	return NewSimpleElement("hr", c...)
}
func Img(c ...interface{}) *Element {
	return NewSimpleElement("img", c...)
}
func Input(c ...interface{}) *Element {
	return NewSimpleElement("input", c...)
}
func Keygen(c ...interface{}) *Element {
	return NewSimpleElement("keygen", c...)
}
func Link(c ...interface{}) *Element {
	return NewSimpleElement("link", c...)
}
func Meta(c ...interface{}) *Element {
	return NewSimpleElement("meta", c...)
}

func Charset(v string) *Attribute { return &Attribute{Name: "charset", Val: v} }
func Class(v string) *Attribute   { return &Attribute{Name: "class", Val: v} }
func Content(v string) *Attribute { return &Attribute{Name: "content", Val: v} }
func Href(v string) *Attribute    { return &Attribute{Name: "href", Val: v} }
func Id(v string) *Attribute      { return &Attribute{Name: "id", Val: v} }
func Lang(v string) *Attribute    { return &Attribute{Name: "lang", Val: v} }
func Name(v string) *Attribute    { return &Attribute{Name: "name", Val: v} }
func Rel(v string) *Attribute     { return &Attribute{Name: "rel", Val: v} }
func Src(v string) *Attribute     { return &Attribute{Name: "src", Val: v} }
func Type(v string) *Attribute    { return &Attribute{Name: "type", Val: v} }
