package doctype

// generated by internal/dog.go
func Head(c ...interface{}) *Tag {
	return NewTag("head", c...)
}
func Body(c ...interface{}) *Tag {
	return NewTag("body", c...)
}
func P(c ...interface{}) *Tag {
	return NewTag("p", c...)
}
func Div(c ...interface{}) *Tag {
	return NewTag("div", c...)
}
func Section(c ...interface{}) *Tag {
	return NewTag("section", c...)
}
func Article(c ...interface{}) *Tag {
	return NewTag("article", c...)
}
func H1(c ...interface{}) *Tag {
	return NewTag("h1", c...)
}
func H2(c ...interface{}) *Tag {
	return NewTag("h2", c...)
}
func H3(c ...interface{}) *Tag {
	return NewTag("h3", c...)
}
func H4(c ...interface{}) *Tag {
	return NewTag("h4", c...)
}

func Meta(c ...interface{}) *Tag {
	return NewSimpleTag("meta", c...)
}
func Img(c ...interface{}) *Tag {
	return NewSimpleTag("img", c...)
}

func Src(v string) *Attr     { return &Attr{name: "src", val: v} }
func Lang(v string) *Attr    { return &Attr{name: "lang", val: v} }
func Charset(v string) *Attr { return &Attr{name: "charset", val: v} }
func Name(v string) *Attr    { return &Attr{name: "name", val: v} }
func Content(v string) *Attr { return &Attr{name: "content", val: v} }
